brew "git"
brew "tmux"
brew "vim"
brew "neovim"
brew "stow"
brew "ripgrep"
brew "fd"
brew "fzf"
brew "bat"
brew "eza"
brew "starship"
brew "zsh-autosuggestions"

cask "ghostty"
cask "font-jetbrains-mono-nerd-font"