alias ll="ls -lah"
alias la="ls -A"
alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias gp="git push"
alias v="vim"
alias t="tmux"
alias clyde="export CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1 && export ENABLE_LSP_TOOLS=1 &&claude --dangerously-skip-permissions --model opus"